/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel;


import javax.swing.JOptionPane;

/**
 *
 * @author kshitiz chahar
 */
public class FeesCalculate extends javax.swing.JFrame {

    /**
     * Creates new form FeesCalculate
     */
    public FeesCalculate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        roto = new javax.swing.JComboBox<>();
        feedu = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gym = new javax.swing.JTextField();
        mess = new javax.swing.JTextField();
        hostel = new javax.swing.JTextField();
        totalfees = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Room Type:-");

        jLabel2.setText("Fees Duration:-");

        roto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "AC (SINGLE)", "AC (DOUBLE)", "NON-AC (SINGLE)", "NON-AC (DOUBLE)" }));

        feedu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "6 Month", "1 Year" }));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Gym:-");

        jLabel4.setText("Mess:-");

        jLabel5.setText("Hostel:-");

        jLabel6.setText("Total Fees:-");

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jButton1)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(feedu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gym)
                            .addComponent(mess)
                            .addComponent(hostel)
                            .addComponent(totalfees))))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(roto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(feedu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(gym, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hostel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalfees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        if(roto.getSelectedItem().equals("AC (SINGLE)"))
        {
           if(feedu.getSelectedItem().equals("6 Month"))
           {
            gym.setText(" Rs: 15000");
            mess.setText("Rs: 25000");
            hostel.setText("Rs: 75000");
            totalfees.setText("Rs: 115000");
           } 
           
           else if(feedu.getSelectedItem().equals("1 Year"))
           {
            gym.setText(" Rs: 30000");
            mess.setText("Rs: 50000");
            hostel.setText("Rs: 150000");
            totalfees.setText("Rs: 230000");  
           } 
        }
        
        else if(roto.getSelectedItem().equals("AC (Double)"))
        {
           if(feedu.getSelectedItem().equals("6 Month"))
           {
              gym.setText(" Rs: 15000");
            mess.setText("Rs: 25000");
            hostel.setText("Rs: 60000");
            totalfees.setText("Rs: 100000"); 
           } 
           
           else if(feedu.getSelectedItem().equals("1 Year"))
           {
               gym.setText(" Rs: 30000");
            mess.setText("Rs: 50000");
            hostel.setText("Rs: 120000");
            totalfees.setText("Rs: 200000");
           } 
        }
        
        else if(roto.getSelectedItem().equals("NON-AC (SINGLE)"))
        {
           if(feedu.getSelectedItem().equals("6 Month"))
           {
              gym.setText(" Rs: 15000");
            mess.setText("Rs: 25000");
            hostel.setText("Rs: 45000");
            totalfees.setText("Rs: 85000");
           } 
           
           else if(feedu.getSelectedItem().equals("1 Year"))
           {
               gym.setText(" Rs: 30000");
            mess.setText("Rs: 50000");
            hostel.setText("Rs: 90000");
            totalfees.setText("Rs: 170000");
           } 
        }
           else if(roto.getSelectedItem().equals("NON-AC (DOUBLE)"))
        {
           if(feedu.getSelectedItem().equals("6 Month"))
           {
              gym.setText(" Rs: 15000");
            mess.setText("Rs: 25000");
            hostel.setText("Rs: 25000");
            totalfees.setText("Rs: 65000");
           } 
           
           else if(feedu.getSelectedItem().equals("1 Year"))
           {
              gym.setText(" Rs: 30000");
            mess.setText("Rs: 50000");
            hostel.setText("Rs: 50000");
            totalfees.setText("Rs: 130000");
           } 
           
          
           
           
        }
        
        
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
                }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Fees fe=new Fees();
        fe.stuname.setText(Detail.sname.getText());
         fe.garname.setText(Detail.gname.getText());
          fe.garphn.setText(Detail.gphn.getText());
           fe.rono.setText(Detail.roomno.getText());
            fe.roty.setText(Detail.roomtype.getText());
             fe.cours.setText(Detail.course.getText());
              fe.semister.setText(Detail.semi.getText());
           
           fe.gf.setText(gym.getText());
           fe.mf.setText(mess.getText());
           fe.hf.setText(hostel.getText());
           fe.tf.setText(totalfees.getText());
           
           fe.setVisible(true);
           dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeesCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeesCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeesCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeesCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeesCalculate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> feedu;
    private javax.swing.JTextField gym;
    private javax.swing.JTextField hostel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mess;
    private javax.swing.JComboBox<String> roto;
    private javax.swing.JTextField totalfees;
    // End of variables declaration//GEN-END:variables
}
