package hostel;






import hostel.Forgot_Password;
import java.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kshitiz chahar
 */
public class login extends javax.swing.JFrame{

    /**
     * Creates new form login
     */
     public login() {
        initComponents();
        currentDate();
     }
    public void currentDate (){
        
        Calendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        Date.setText((month+1)+"/"+day+"/"+year);
        
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
        time.setText(hour+":"+(minute)+":"+second);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        sign_up = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        fpass = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        aid = new javax.swing.JTextField();
        apass = new javax.swing.JPasswordField();
        cpass = new javax.swing.JPasswordField();
        phn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        aname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar4 = new javax.swing.JMenuBar();
        Date = new javax.swing.JMenu();
        time = new javax.swing.JMenu();

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setText("User Name:-");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 210, 100, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setText("Password:-");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 250, 110, 17);

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(210, 360, 63, 25);

        name.setForeground(new java.awt.Color(51, 51, 51));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(200, 210, 235, 22);
        jPanel1.add(password);
        password.setBounds(200, 250, 235, 22);

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/images.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 0, 360, 150);

        fpass.setText("Forgot Password");
        fpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpassActionPerformed(evt);
            }
        });
        jPanel1.add(fpass);
        fpass.setBounds(299, 360, 130, 25);

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(80, 360, 59, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/pexels-photo-1227520.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 460, 440);

        sign_up.addTab("Login", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("Admin Id:-");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(90, 120, 80, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 204));
        jLabel6.setText("Password:-");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(90, 270, 90, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 204));
        jLabel7.setText("Conform Password:-");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 340, 150, 16);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 204));
        jLabel8.setText("Phone no:-");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(90, 190, 90, 17);

        signup.setBackground(new java.awt.Color(0, 204, 204));
        signup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signup.setText("Sign Up");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        jPanel3.add(signup);
        signup.setBounds(170, 410, 85, 25);

        aid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aidActionPerformed(evt);
            }
        });
        jPanel3.add(aid);
        aid.setBounds(190, 120, 230, 30);
        jPanel3.add(apass);
        apass.setBounds(190, 260, 230, 30);

        cpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpassActionPerformed(evt);
            }
        });
        jPanel3.add(cpass);
        cpass.setBounds(190, 330, 230, 30);
        jPanel3.add(phn);
        phn.setBounds(190, 180, 230, 30);
        jPanel3.add(jLabel10);
        jLabel10.setBounds(37, 62, 0, 0);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 153));
        jLabel9.setText("Admin Name:-");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(70, 57, 99, 30);
        jPanel3.add(aname);
        aname.setBounds(190, 60, 230, 30);

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 153));
        jLabel14.setText("New Admin");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(150, 10, 140, 25);

        jLabel12.setOpaque(true);
        jPanel3.add(jLabel12);
        jLabel12.setBounds(0, 0, 440, 460);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sign_up.addTab("New Admin", jPanel2);

        Date.setText("Date");
        jMenuBar4.add(Date);

        time.setText("Time");
        jMenuBar4.add(time);

        setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sign_up, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sign_up, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aidActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_nameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        try{
            Connection con;
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Hostel_info", "app", "root");
            String s1="SELECT * FROM ADMIN_INFO ";
           Statement creatStatement= con.createStatement();
           
            int flag=0;
            ResultSet rs =creatStatement.executeQuery(s1);
           while(rs.next()){
               if(rs.getString("ADMIN_NAME").equals(name.getText()))
               {
                   if(rs.getString("PASSWORD").equals(password.getText()))
                   {
                       JOptionPane.showMessageDialog(this,"Welcome Admin");
                      student s=new student();
                      s.setVisible(true);
                      dispose();
                      flag=1;
                      break;
              
                   }
                   
                   else
                   {
                      JOptionPane.showMessageDialog(null, "Invalid Password");
                   }
               }
               else{
               }
                       
            
            }
           if (flag!=1)
           {
           JOptionPane.showMessageDialog(null,"INvalid username");
           }
            
               
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        try{
           Connection con;
           con = DriverManager.getConnection("jdbc:derby://localhost:1527/Hostel_info", "app", "root");
           PreparedStatement pstmt; 
            pstmt = con.prepareStatement("insert into ADMIN_INFO(ADMIN_NAME, ADMIN_ID, PASSWORD, PHONE_NO ) values(?,?,?,?)");
    
            
            if(aname.getText().trim().isEmpty())
            {
              JOptionPane.showMessageDialog(this,"Enter the Name");  
            }
            else{
                pstmt.setString(1,aname.getText() );
            }
            if(apass.getText().trim().isEmpty()){ 
                apass.getText().equals(cpass.getText());
                        
                JOptionPane.showMessageDialog(this,"Enter the Password");
            }
            else{
                pstmt.setString(3,apass.getText());
            }
            if(aid.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this,"Enter the Admin Id");
            }
            else{
                pstmt.setString(2,aid.getText());
            }
             if(phn.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this,"Enter the Phone no");
            }
            else{
                pstmt.setString(4,phn.getText());
            }
            
             
         pstmt.executeUpdate();
         JOptionPane.showMessageDialog(this," Admin Sign  Up"); 
        }
        catch(SQLException e){
          JOptionPane.showMessageDialog(null, e);  
        }
        
    }//GEN-LAST:event_signupActionPerformed

    private void cpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpassActionPerformed

    private void fpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpassActionPerformed
        // TODO add your handling code here:
         
         try {
           Forgot_Password  f = new  Forgot_Password ();
             f.setVisible(true);
             dispose();
         } catch (Exception e) {
          
         }
        
    }//GEN-LAST:event_fpassActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        mainpage m =new mainpage();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Date;
    private javax.swing.JTextField aid;
    private javax.swing.JTextField aname;
    private javax.swing.JPasswordField apass;
    private javax.swing.JButton back;
    private javax.swing.JPasswordField cpass;
    private javax.swing.JButton fpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton login;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phn;
    private javax.swing.JTabbedPane sign_up;
    private javax.swing.JButton signup;
    private javax.swing.JMenu time;
    // End of variables declaration//GEN-END:variables

    private static class Student {

     

    private static class stu {

        public stu() {
        }
    }

 
   
    }}
